sudo: required
services:
    - docker
    
before_install:
    - docker build -t steve1234/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true steve1234/docker-react npm run test -- --coverage