sudo: required
services:
    - docker
    
before_install:
    - docker build -t steve1234/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true steve1234/docker-react npm run test -- --coverage
    
deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-958396123372"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: 
        secure: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"